lclstreamer:
    source_identifier: exp=xpptut15:run=430
    batch_size: 1
    event_source: Psana1EventSource
    processing_pipeline: NoOpProcessingPipeline
    data_serializer: Hdf5Serializer
    data_handlers:
        - BinaryFileWritingDataHandler
          #- BinaryDataStreamingDataHandler

data_sources:
    timestamp:
        type: Psana1Timestamp

    detector_data:
        type: Psana1AreaDetector
        psana_name: Jungfrau1M
        calibration: true

    random:
        type: GenericRandomNumpyArray
        array_shape: 4,4,4
        array_dtype: int8



event_source:
    Psana1EventSource: {}

processing_pipeline:
    NoOpProcessingPipeline: {}

data_serializer:
    Hdf5Serializer:
        compression_level: 3
        compression: null
        fields:
            timestamp: /data/timestamp
            detector_data: /data/data
            random: /data/random

data_handlers:
    BinaryFileWritingDataHandler:
        file_prefix: ""
        file_suffix: h5
        write_directory: /sdf/home/v/valmar/Projects/lclstreamer/workspace/output

    BinaryDataStreamingDataHandler:
        urls:
            - "tcp://sdfdtn003:5000"
        role: client
        library: nng
        socket_type: push
