lclstreamer:
    source_identifier: exp=mfx100903824:run=27
    event_source: Psana1EventSource
    processing_pipeline: PeaknetPreprocessingPipeline
    data_serializer: Hdf5BinarySerializer
    skip_incomplete_events: false
    data_handlers:
        - BinaryDataStreamingDataHandler

data_sources:
    timestamp:
        type: Psana1Timestamp

    detector_data:
        type: Psana1AssembledAreaDetector
        psana_name: epix10k2M

    random:
        type: GenericRandomNumpyArray
        array_shape: 4,4,4
        array_dtype: float32

    photon_wavelength:
        type: Psana1PV
        psana_name: "SIOC:SYS0:ML00:AO192"

event_source:
    Psana1EventSource: {}

processing_pipeline:
    PeaknetPreprocessingPipeline:
        batch_size: 16
        target_height: 2048
        target_width: 2048
        pad_style: center
        add_channel_dim: true
        num_channels: 1

data_serializer:
    Hdf5BinarySerializer:
        compression_level: 3
        compression: zfp
        fields:
            timestamp: /data/timestamp
            detector_data: /data/data
            random: /data/random
            photon_wavelength: /data/wavelength

data_handlers:
    BinaryDataStreamingDataHandler:
        urls:
            - "tcp://sdfada001:12321"
        role: client
        library: nng
        socket_type: push