lclstreamer:
    source_identifier: exp=tmox1016823,run=45
    event_source: Psana2EventSource
    processing_pipeline: BatchProcessingPipeline
    data_serializer: Hdf5Serializer
    skip_incomplete_events: True
    data_handlers:
        - BinaryFileWritingDataHandler
          #- BinaryDataStreamingDataHandler

data_sources:
    timestamp:
        type: Psana2Timestamp

    random:
        type: GenericRandomNumpyArray
        array_shape: 4,4,4
        array_dtype: float32

event_source:
    Psana2EventSource: {}

processing_pipeline:
    BatchProcessingPipeline:
        batch_size: 10

data_serializer:
    Hdf5Serializer:
        compression_level: 3
        compression: zfp
        fields:
            timestamp: /timestamp
            photon_wavelength: /wavelength
            random: /drandom

data_handlers:
    BinaryFileWritingDataHandler:
        write_directory: workspace/output

    BinaryDataStreamingDataHandler:
        urls:
            - "tcp://sdfdtn003:5000"
        role: client
        library: nng
        socket_type: push
