lclstreamer:
    source_identifier:
       exp: tmox1016823
       run: 45
    batch_size: 1
    event_source: Psana2EventSource
    processing_pipeline: NoOpProcessingPipeline
    data_serializer: Hdf5Serializer
    skip_incomplete_events: True
    data_handlers:
        - BinaryFileWritingDataHandler
          #- BinaryDataStreamingDataHandler

data_sources:
    timestamp:
        type: Psana2Timestamp

#   detector_data:
#       type: Psana2SpectralDetector
#       psana_name: Z_piranha
#       calibration: false

    random:
        type: GenericRandomNumpyArray
        array_shape: 4,4,4
        array_dtype: float32

event_source:
    Psana2EventSource: {}

processing_pipeline:
    NoOpProcessingPipeline: {}

data_serializer:
    Hdf5Serializer:
        compression_level: 3
        compression: zfp
        fields:
            timestamp: /data/timestamp
            random: /data/random
            #detector_data: /data/data
            #photon_wavelength: /data/wavelength

data_handlers:
    BinaryFileWritingDataHandler:
        write_directory: /sdf/home/r/rogersdd/lclstreamer-output

    BinaryDataStreamingDataHandler:
        urls:
            - "tcp://sdfdtn003:5000"
        role: client
        library: nng
        socket_type: push
