site_name: "LCLStreamer: Data Retrieval and Streaming at LCLS"
site_url: https://slac-lcls.github.io/lclstreamer/
repo_url: https://github.com/slac-lcls/lclstreamer
markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
theme:
    name: material
    palette:
        primary: deep purple
    features:
        - content.code.copy
        - navigation.expand
nav:
    - "LCLStreamer":
          - "Introduction": index.md
          - "LCLStreamer Data Workflow": lclstreamer_data_workflow.md
    - "Installation / Running": installation_running.md
    - "Configuration":
          - "LCLStreamer": configuration_lclstreamer.md
          - "Event Sources": configuration_event_sources.md
          - "Processing Pipelines": configuration_processing_pipelines.md
          - "Data Serializers": configuration_data_serializers.md
          - "Data Handlers": configuration_data_handlers.md
          - "Data Sources": configuration_data_sources.md
